# cw2 config
name: hopper_seq_entire
import_path: "./shared_hopper.yaml"
import_exp: "hopper_seq_entire"

repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: &iterations 15000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 1
      num_env_test: 4
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations